box:
  properties:
    size:
      x: 0.25
      y: 0.25
      z: 0.25
    COM:            #relative to geometric center
      x: 0.0
      y: 0.0
      z: 0.0
    mass: 0.3
    mu: 0.025
    mu2: 0.025
  initial_pos:
    x: 0.0
    y: -0.8
    z: 0.175
  

table:
  properties:
    size:
      x: 0.8
      y: 3.0
      z: 0.05
    COM:
      x: 0.0
      y: 0.0
      z: 0.0
    mass: 100
    mu: 0.1
    mu2: 0.1
  initial_pos:
    x: 0.0
    y: 0.0
    z: 0.025

#hit:
#  speed: 1.0
#  direction: 0.0
