object_real: false
iiwa_real: false
manual_mode: false
hollow: false


#average of desired workspace of iiwa1 wrt world frame. In real, world frame is exactly between iiwa_base so centers should have x =/= 0
center1: [0.55, -0.45, 0.165]  #z is center of box
center2: [0.55, 0.45, 0.165]

ee_offset:
  h: 0.4                # horizontal offset for the end effector behind the object's center before moving to hit
  v: 0.225              # vertical offset

hittable:      # to create a hittable area in the form of an ellipsoid with its center at an offset from center1 (or center2)
  reach:
    x: 0.15             # perp to centerline     
    y: 0.25             # along centerline
  offset: 
    x: 0.0              # currently not useful as it flips x direction for other robot
    y: 0.1              # positive is inwards along centerline

table:
  properties:           # keep in mind that the iiwa base has a max radius of 0.3
    size:
      x: 0.8
      y: 2.0
      z: 0.05
    COM:
      x: 0.0
      y: 0.0
      z: 0.0
    mass: 100
    mu: 0.5
    mu2: 0.5
  initial_pos:
    x: 0.55
    y: 0.0
    z: 0.025

box:
  properties:
    size:
      x: 0.26
      y: 0.26
      z: 0.23
    COM:            #relative to geometric center
      x: 0.0
      y: 0.0
      z: 0.0
    mass: 0.363
    mu: 0.045
    mu2: 0.045
  initial_pos:
    x: 0.55
    y: -0.45
    z: 0.175
  
mini:
  properties:
    size:
      x: 0.1
      y: 0.1
      z: 0.1
    COM:            #relative to geometric center
      x: 0.0
      y: 0.0
      z: 0.0
    mass: 0.3
    mu: 0.03
    mu2: 0.03
  initial_pos:      #relative to big box center
    x: 0.0
    y: -0.065
    z: -0.065



#hit:
#  speed: 1.0
#  direction: 0.0
