
passive_control: {
  vel_quat: "/passive_control/vel_quat" # Control velocity - type geometry_msgs::Pose
}

gazebo: {
  model_states: "/gazebo/model_states", # Object position and orientation - type gazebo_msgs::ModelStates
  link_states: "/gazebo/link_states" # Object position and orientation of iiwa links - type gazebo_msgs::LinkStates

}

iiwa: {
  dir_flux: "/iiwa/dir_flux",

  Inertia: {
    taskPos: "/iiwa/Inertia/taskPos"
  }
}
